### ISSUE TITLE
little help or documentation?

### ISSUE THREAD

**Issue by zerger3** [jinzocode/imacros-scripts-niche#3]
i am interested in your twitter scripts but i am not 100% sure what exactly they do and what the datascource files should look like.
i am interested in a script with pauses which follow users on a twitter list :)
as far as i can see your scripts seem to be really good coded

**Comment by jinzocode** [comment]
Hello

I know there is a need for documentation, I'm currently working on it.

Thanks.

**Comment by zerger3** [comment]
would you mind writing a few words for each twitter script so i know what they do? :)

**Comment by jinzocode** [comment]
Done.
